### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-tmux#1]
### Design
The theme should be implemented to match the [Nord Vim](https://github.com/arcticicestudio/nord-vim) port project regarding the layout and UTF8 character design.

### Features and Support
The initial implementation should include styles for the left- and right status bars, the windows and panes.
Furthermore optimized styles for the command line and messages.

### Build- and Development Tools
A configuration for [EditorConfig](http://editorconfig.org) should be added.

### Plugin Manager
The documentation should include instructions on how to install the theme with the plugin manager [tpm](https://github.com/tmux-plugins/tpm).

## Process

  - [x] Right- and left status bars
  - [x] Window status
  - [x] Pane styles
  - [x] Message styles
  - [x] Build Tool Configurations

---

❭**Nord Backlog**: [arcticicestudio/nord #30](https://github.com/arcticicestudio/nord/issues/30)
❭**Related to** [arcticicestudio/nord #16](https://github.com/arcticicestudio/nord/issues/16)

/cc @heliostatic @brandon099 @azmodude

**Comment by kepbod** [comment]
This repo is what I want. Thanks so much to apply nord theme to tmux. I have applied one, and if you are interested, please [have a look](https://github.com/kepbod/kdot/blob/master/tmux.conf#L22-L34). Waiting for the official version.

![screen shot 2017-04-19 at 5 08 46 pm](https://cloud.githubusercontent.com/assets/1172557/25244102/64aff704-25cd-11e7-8a70-b9ffd4bae93e.png)

**Comment by arcticicestudio** [comment]
🚢 Shipped initial release version 🏷 [0.1.0](https://github.com/arcticicestudio/nord-tmux/releases/tag/v0.1.0).
