### ISSUE TITLE
update manual steps

### ISSUE THREAD

**Issue by rgcr** [arcticicestudio/nord-tmux#10]
As I don't want to use `tpm`. I installed your theme manually but we need to source `nord-status-content.conf` also, otherwise the theme does not work as expected

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 

It should generally be changed to make use of the `nord.tmux` loader, I'll update the documentation instructions to advise users to clone the repository and add

```sh
run-shell ~/<PATH_TO_REPOSITORY_CLONE>/nord.tmux
```

to their `~/.tmux.conf` file which is the correct way to automatically source all necessary files and allow to make use of the [available theme configurations](https://github.com/arcticicestudio/nord-tmux#configuration).
