### ISSUE TITLE
rxvt-unicode + tmux + nord

### ISSUE THREAD

**Issue by bigDaddyS1oth** [arcticicestudio/nord-tmux#18]
So I saw this theme series and thought I'd start installing some of the theme, and I installed the tmux theme and the only issue I'm having now is [this](https://i.imgur.com/qcpeaHD.png). 

I'm not entirely sure what I'd need to give you for this, but [here's](https://pastebin.com/MSpc0fH1) my `tmux.conf`.

I want to say it's an issue with line 84 

    set -g default-terminal "screen-256color"

or that I need to specify for tmux to use UTF-8?

or does the styling in the nord plugin not work with rxvt-unicode?

**Comment by delphinus** [comment]
You mean, your problem is the square glyphs (so-called “Tofu”) in the statusline?  You should set Powerline-style patched font in the setting of terminal app (rxvt).  What font are you using?

And you can use non-patched font with `set -g @nord_tmux_no_patched_font "1"` option.  It simply removes the “Tofu”s.

**Comment by arcticicestudio** [comment]
@bigDaddyS1oth Any progress, have you been able to fix the problem with the instructions posted by @delphinus?

**Comment by bigDaddyS1oth** [comment]
Oh my god, so sorry. 

Well I had DejaVu Sans Mono as my fonts in my `~/.Xresources` file, and I don't recall if I've had issues with unicode characters when using it. I just tried switching to Source Code Pro, and the ">"-esque parts of the TMUX status bar are there, but not some miscellaneous characters (they show up as "[]"). I'll try adding those options to my `~/.tmux.conf`

**Comment by arcticicestudio** [comment]
Nice to hear that you fixed it. Sadly rxvt is known to make problems when it comes to encoding and also color (e.g. TrueColor support). Maybe rxvt only supports fixed size glyphs which are available in the installed font at size 15.

I'll close this for now. Feel free to reopen or post here if you've been able to chase down the origin of the problem.
