### ISSUE TITLE
Weird symbols in status bar.

### ISSUE THREAD

**Issue by davidrthorn** [arcticicestudio/nord-tmux#21]
I'm getting weird symbols in my tmux status bar instead of arrows:

![screenshot_2018-01-07_10-52-50](https://user-images.githubusercontent.com/9431760/34648841-1ea1fea6-f39a-11e7-8f7f-a739d9a578f7.png)

Running tmux in xfce terminal on Xubuntu 17.04
Installed nord-tmux through tpm
Font: Source Code Medium installed via Google Fonts

**Comment by jkawamoto** [comment]
I think you need patched fonts. You can download patched Source Code Pro fonts from https://github.com/powerline/fonts/tree/master/SourceCodePro

**Comment by arcticicestudio** [comment]
@davidrthorn Can you please try if it works when using Source Code Pro from the [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts) project?

**Comment by davidrthorn** [comment]
I installed nerd font and then adobe. Now the symbols work, but xfce terminal does not display the fonts properly. Letters overlap, it's a mess. I think I'll have to tolerate the missing symbols.

**Comment by arcticicestudio** [comment]
@davidrthorn Ty to use different font sizes. A user with a similar problem solved it by changing the font size from `14` to `15` as described in https://github.com/arcticicestudio/nord-tmux/issues/18#issuecomment-354303824

**Comment by davidrthorn** [comment]
Tried already, no success. Same problem in gnome-terminal

**Comment by arcticicestudio** [comment]
So I've currently no more idea what's the origin of this problem. You can remove the corrupted glyphs by using the [theme configuration to disable patched fonts][ref].

[ref]: https://github.com/arcticicestudio/nord-tmux#no-patched-fonts

**Comment by davidrthorn** [comment]
@arcticicestudio Thank you for trying :) If I fix it I'll let you know how

**Comment by davidrthorn** [comment]
OK, final stab succeeded. I think it was just the font choice. Downloaded font directly from Nerd Font website (not GitHub) and chose Terminus rather than Source Code Pro. Now working.

**Comment by arcticicestudio** [comment]
Nice to hear it works fine now :smile:
