### ISSUE TITLE
Support for tmux-prefix-highlight

### ISSUE THREAD

**Issue by kepbod** [arcticicestudio/nord-tmux#3]
Thanks for very great repo. I think it would be better to support [tmux-prefix-highlight](https://github.com/tmux-plugins/tmux-prefix-highlight) which could highlight when pressing tmux prefix key to indicate whether you press the prefix key. I have tested that if you did not install this plugin, the status line would not be influenced, so it is compatible for people who do not love it.

**Comment by arcticicestudio** [comment]
Thanks for the proposal 👍 
This looks like a nice optional addition. Maybe I'll also implement it as a configuration so users can enable or disable it via a boolean in their `~/.tmux.conf`.

**Comment by arcticicestudio** [comment]
🚢 Shipped with plugin release version 🏷 [0.2.0](https://github.com/arcticicestudio/nord-tmux/releases/tag/v0.2.0).
