### ISSUE TITLE
Custom right status content 

### ISSUE THREAD

**Issue by Joshgallagher** [arcticicestudio/nord-tmux#35]
Hi,

I'm having a little bit of an issue.

I have customised the right status content to include some extra plugins. However, when I restart my computer, the left status content looses its theming.

Left status content after restart:
<img width="159" alt="Screenshot 2019-05-28 at 16 59 06" src="https://user-images.githubusercontent.com/5052591/58493023-feeced00-8169-11e9-8d74-5883de021e04.png">

However, the right side is fine:
<img width="297" alt="Screenshot 2019-05-28 at 17 00 14" src="https://user-images.githubusercontent.com/5052591/58493110-28a61400-816a-11e9-9a36-ebba7f2d8788.png">

My tmux conf:

```
# Remap prefix from 'C-b' to 'C-space'
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'arcticicestudio/nord-tmux'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'

# Enable mouse mode
set -g mouse on

# Set default icons for battery plugin 
set -g @batt_charged_icon "😎 "
set -g @batt_charging_icon "👍 "
set -g @batt_attached_icon "😐 "
set -g @batt_full_charge_icon "🌕 "
set -g @batt_high_charge_icon "🌖 "
set -g @batt_medium_charge_icon "🌗 "
set -g @batt_low_charge_icon "🌘 "

# Set prefix text for prefix and copy modes
set -g @prefix_highlight_prefix_prompt " Prefix " 
set -g @prefix_highlight_copy_prompt " Copy "

# Setup right status bar
set -g status-right-length "60"
set -g @nord_tmux_show_status_content "0"

set -g status-right "#{prefix_highlight}#[fg=brightblack,bg=black,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack] #{battery_icon}#{battery_percentage}  #{cpu_icon} #{cpu_percentage} #[fg=white,bg=brightblack,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack] %I:%M%p #[fg=cyan,bg=brightblack,nobold,noitalics,nounderscore]#[fg=black,bg=cyan,bold] #H "

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
```

I can solve this issue manually through these steps:

Step 1: Change this `set -g @nord_tmux_show_status_content "0"` to `set -g @nord_tmux_show_status_content "1"` and then run `tmux source-file ~/.tmux.conf`.
Step 2: Change `set -g @nord_tmux_show_status_content "1"` back to `set -g @nord_tmux_show_status_content "0"` and then re-run `tmux source-file ~/.tmux.conf`.

This gives me the result I want:
<img width="1041" alt="Screenshot 2019-05-28 at 17 09 07" src="https://user-images.githubusercontent.com/5052591/58493654-56d82380-816b-11e9-8387-0b500a9efb81.png">

However, this is annoying...

Thanks in advance and love everything artic!

**Comment by CharlesConner** [comment]
If you look at `nord.tmux` in the root directory of this project you can see that there is a check for whether the user has set `show_status_content` or not. If you have set it to zero it wont source the other files inside of `src` directory. 

What you can do is copy paste the contents of either `nord-status-content.conf` or `nord-status-content-no-patched-font.conf`(depending on if you want the patched font or not) to your tmux.conf file, or if you dont want to copy paste the content to your own config file you could just source the file yourself.

**Comment by Joshgallagher** [comment]
Sourcing `nord-status-content.conf` fixed the issue @CharlesConner. Thanks!

**Comment by karl-gustav** [comment]
Simplest solution is to override both left and right statuses and setting `set -g @nord_tmux_show_status_content "0"` to prevent nordtheme from overriding them again.
