### ISSUE TITLE
Allow disabling the use of patched fonts

### ISSUE THREAD

**Issue by petrhosek** [arcticicestudio/nord-tmux#5]
It'd be useful to make the use of patched fonts optional (same as in [lightline](https://github.com/itchyny/lightline.vim)).

**Comment by arcticicestudio** [comment]
Sorry for my late reply, I've been busy with my job.
I'll check if it is possible to implement theme settings to add a option to disable the symbold from the status bar.

---

> **Related to** #7

**Comment by arcticicestudio** [comment]
@petrhosek Sorry for the delay again. I've implemented a configuration to disable the usage of patched fonts for the status content in #11.
