### ISSUE TITLE
tmux prefix highlight should not patch font when no_patch_font setting enabled

### ISSUE THREAD

**Issue by wingyplus** [arcticicestudio/nord-tmux#51]
![Screen Shot 2563-08-18 at 22 32 52](https://user-images.githubusercontent.com/484530/90533638-fdf70f80-e1a2-11ea-8811-19542ee78b84.png)

In the image above. prefix highlight plugin display like a patch font setting disabled.

**Comment by wingyplus** [comment]
`tmux kill-server` solve this issue. Sorry for the noise.

**Comment by arcticicestudio** [comment]
No problem, good to see it works fine now 😄
