### ISSUE TITLE
Nord Tmux preventing other application colours from showing

### ISSUE THREAD

**Issue by paulalden** [arcticicestudio/nord-tmux#54]
Hello. This seems kinda silly, but nord tmux seems to be preventing Vim colour schemes from working. 

I've followed all of the installation instructions and added a terminal theme to Gnome Terminal and Tmux its self looks great, but whenever its running, vim colour schemes seem to be suppressed and aren't showing as anything more than basic white text. 

Vim without Tmux:
![image](https://user-images.githubusercontent.com/1199977/103462664-ad7dea00-4d1e-11eb-88ab-5c3c275dd6d6.png)

Vim inside of Tmux, without terminal theme: 
![image](https://user-images.githubusercontent.com/1199977/103462678-df8f4c00-4d1e-11eb-9437-9dcc7a8b61f0.png)

Vim inside of Tmux, with terminal running nord theme: 
![image](https://user-images.githubusercontent.com/1199977/103462705-14030800-4d1f-11eb-8e43-cd508d2e17e3.png)

**Comment by paulalden** [comment]
I dont think its related to the theme, seems to be an issue with Tmux generally :-/

**Comment by arcticicestudio** [comment]
Hi @prdanelli 👋🏼 

Running applications that provide highlighting within _tmux_ is a bit tricky and requires some extra configurations.
In case of Vim you can check out some issues in the repository of the Nord Vim port project, e.g. arcticicestudio/nord-vim#166 that includes some details about required _tmux_ settings in your `vimrc` as well as general environment variables.

**Comment by paulalden** [comment]
@arcticicestudio Thank you for replying. I figured it out in the end: 

```
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set background=dark
" This line MUST come after the colors scheme settings above
colorscheme nord
```

The order of the settings made a massive difference and I needed to set the special characters above everything else.
