### ISSUE TITLE
the theme does not work

### ISSUE THREAD

**Issue by Hugo-Oliveira-RD11** [arcticicestudio/nord-tmux#56]
firstly I'm using google translator, because I'm Brazilian and i still don't know English (that is, you can see mistakes in the translation)
secondly, my tmux n is working with your theme, it gets all buggy 
![MyTmux](https://github.com/Hugo-Oliveira-RDO11/teste/blob/master/Mytmux.png)
(I don't know how to let the image appear in the issue)
this image and after I install the tmp and press the prefix and I, to install the nord

**Comment by Hugo-Oliveira-RD11** [comment]
I fixed it, but it wasn't for your theme (nord), but I think it will work, the problem was the source of the powerline (or airline, I don't know who it is ...), which has very different uni-codes ...
RESOLUTION
I downloaded the powerline font (the corrected one!), and configured it for my terminal to show this font, and it worked ...
Well, as I said above, it wasn’t about the Nord theme, it was on the airline, but I think if someone has the same problem, if you follow these steps, fix it. (If someone wants me to detail more about how I solved it and just talk )

attention: this text was translated on google translator, there will be a lot of errors!

**Comment by arcticicestudio** [comment]
Hi @Hugo-Oliveira-RDO11 :wave:
Nice to see that it works fine for you now.

There is a section about [font rendering and  possible issues][d1] as well as information about how to opt-out from the need to use a [patched font for Unicode characters][d2]. Even though you already fixed it on your side, I wanted to leave this here as reference for other users running into the same problem again  😄 

[d1]: https://www.nordtheme.com/docs/ports/tmux/configuration#font-rendering
[d2]: https://www.nordtheme.com/docs/ports/tmux/configuration#patched-font-characters
