### ISSUE TITLE
Weird rendering... Is the problem my font?

### ISSUE THREAD

**Issue by wantyapps** [arcticicestudio/nord-tmux#57]
<img width="1440" alt="Screen Shot 2021-03-14 at 10 28 29" src="https://user-images.githubusercontent.com/56798701/111062203-2ed8c200-84b0-11eb-81c6-8cc519624d12.png">

As you can see, something is wrong with the rendering. I use the font JetBrains Mono, and it doesn't quite work. Also tried the font in the screenshots (which is source code pro) and the problem still occurred.

Any help?

**Comment by wantyapps** [comment]
(macOS Big Sur 11.2.2)

**Comment by RomelSan** [comment]
Try a NerdFont. If problem still the same... then try another Terminal App.

**Comment by wantyapps** [comment]
Tried in Terminal.app (Mac default) still even worse

**Comment by wantyapps** [comment]
Is there a JetBrains Mono Nerd Font?

**Comment by wantyapps** [comment]
Did not work. Searching for another font.

**Comment by arcticicestudio** [comment]
Hi @wantyapps 👋🏼 
Like @RomelSan  already mentioned, you need to make to use a [patched font][d-pfc] when using the default bar configuration of this theme. Please make sure to read [Nord tmux's documentation about font rendering][d-fr] for more details.

[d-fr]: https://www.nordtheme.com/docs/ports/tmux/configuration#font-rendering
[d-pfc]: https://www.nordtheme.com/docs/ports/tmux/configuration#patched-font-characters

**Comment by wantyapps** [comment]
Thank you @arcticicestudio

**Comment by wantyapps** [comment]
<img width="1440" alt="Screen Shot 2021-03-15 at 9 29 34" src="https://user-images.githubusercontent.com/56798701/111118043-f64ced00-8570-11eb-8328-f530e595e104.png">

Clicked on your (patched font) link in the message

**Comment by arcticicestudio** [comment]
Ups, missed the `#` sign to link to the headline.
It's fixed in the comment above.

**Comment by arcticicestudio** [comment]
@wantyapps Did you manage to fix your setup?

**Comment by wantyapps** [comment]
Nah I didn't. None of the nerd fonts worked and I quit.

**Comment by wantyapps** [comment]
But thanks for helping.

**Comment by arcticicestudio** [comment]
In the end you can still [disable patched font characters for this theme][1] or [disable the pre-defined status line content][2] at all to use your own one.
I'll close this issue here now since this a local problem and not a bug in the theme.

[1]: https://www.nordtheme.com/docs/ports/tmux/configuration#patched-font-characters
[2]: https://www.nordtheme.com/docs/ports/tmux/configuration#default-status-bar-content
