### ISSUE TITLE
Tmux Configuration Weird Loading

### ISSUE THREAD

**Issue by 0xd4y** [arcticicestudio/nord-tmux#58]
I am on a ParrotOS machine using the MATE terminal. Unfortunately, the tmux configuration does not work for me. Also, when I try to use the nord-vim colorscheme, the colors end up being completely different from what is expected.

![image](https://user-images.githubusercontent.com/77868212/113428657-ca1cd300-939c-11eb-9da5-a14c5d8b1a43.png)

I'd really appreciate your help!

**Comment by 0xd4y** [comment]
I know that it is probably a problem with the incompatibility of the MATE terminal emulator. Which terminal emulator worked for you?

**Comment by arcticicestudio** [comment]
Hi @0xd4y :wave:

Based on the colors from the screenshot, it looks like you're missing the required theme for the terminal. tmux uses the colors provided by the terminal so a Nord theme for the terminal must be installed too (note the information [box at the top of the Nord tmux installation documentation][3]). 

I did a quick research and MATE seems to be a fork from [GNOME Terminal][1] so you can try to install [Nord for GNOME terminal][2].

[1]: https://help.gnome.org/users/gnome-terminal/stable
[2]: https://github.com/arcticicestudio/nord-gnome-terminal
[3]: https://www.nordtheme.com/docs/ports/tmux/installation
