### ISSUE TITLE
A bit more than a color scheme plugin

### ISSUE THREAD

**Issue by tsroten** [arcticicestudio/nord-tmux#7]
First, thanks for the awesome color scheme. I've never been happy with a color scheme until I found nord 😄 .

This particular repo appears to be more than a color scheme, though. It actually sets the status bar content. This makes it impossible to override the status bar successfully while using plugins like prefix highlight. Have you considered making this strictly a color scheme plugin? Like, something similar to https://github.com/seebi/tmux-colors-solarized, where things like the content of `status-right` are left up to the user? It seems a bit odd that a color scheme plugin would actually dictate the content of the status bar itself.

**Comment by arcticicestudio** [comment]
Sorry for my late reply, I've been busy with my job.
I'll check if it is possible to implement theme settings to add a option to disable the entire status bar styling.

---

> **Related to** #5

**Comment by tsroten** [comment]
@arcticicestudio Thanks for the response! I've submitted a [PR](https://github.com/arcticicestudio/nord-tmux/pull/8) that allows the user to disable all status bar *content*, while keeping the actual color-related settings.

**Comment by arcticicestudio** [comment]
Thanks a lot for the PR, it really help me a lot to get things done more quickly
 if people are actually contribute :+1: 
I've merged it and will prepare a new release version as soon as possible.
