### ISSUE TITLE
Trouble with develop branch

### ISSUE THREAD

**Issue by possibilities** [arcticicestudio/nord-tmux#82]
When I use the develop branch the colors are completely wrong. But they look good in the master branch. There are a couple small issues I was going to investigate but then I noticed that master hasn't been updated in 4 years. Which branch should I be using?

develop:

![image](https://user-images.githubusercontent.com/502777/231293795-d0a769f3-7071-440c-a62b-e93d8a09c287.png)

**Comment by ericvw** [comment]
Hey @possibilities, are you using the [Quick Start](https://github.com/nordtheme/tmux#quick-start) steps in the README.md? If not, what steps are you using for installation?

> Which branch should I be using?

`develop` is the branch I am using, and it should be like the following:

![Screenshot 2023-04-11 at 17 43 58](https://user-images.githubusercontent.com/1284017/231294896-f11cdf98-27ca-4387-b155-fd4df748cfcb.png)

Also, I want to double-check that your terminal emulator is also using a Nord theme port per https://www.nordtheme.com/docs/ports/tmux/installation:

> tmux must be used with a [Nord terminal emulator theme](https://www.nordtheme.com/ports) in order to work properly!

**Comment by possibilities** [comment]
I'm not sure what I did wrong before because once I started investigating and trying to take more screenshots it seems to all be OK. And the small issues I had are gone also. Thanks for your response and sorry to waste your time.

**Comment by ericvw** [comment]
No worries! I'm glad you are all set 👍.
