### ISSUE TITLE
Status bar is ugly in Mac OS X

### ISSUE THREAD

**Issue by truenicoco** [arcticicestudio/nord-tmux#89]
<img width="819" alt="Capture d’écran 2023-10-01 à 05 49 19" src="https://github.com/nordtheme/tmux/assets/1313576/44b49471-e9d7-4094-8430-7e2b4970794e">

UTF-8 stuff I guess?

**Comment by AmrSaber** [comment]
I think you should see [this reddit thread](https://www.reddit.com/r/nordtheme/comments/w41w1f/missing_fonts_on_macos/) and more specifically [this link](https://www.nordtheme.com/docs/ports/tmux/configuration#font-rendering) they mentioned.

**Comment by truenicoco** [comment]
Oh, I actually looked for that in the docs and couldn't find it 🤦 . Thanks!
