### ISSUE TITLE
Copy Mode Screenshot Incorrect

### ISSUE THREAD

**Issue by tsroten** [arcticicestudio/nord-tmux#9]
It looks like the screenshot in the README for copy mode actually has the colors inverted when you compare it to `nord.conf`.

I'm not sure which one was the intention -- to match the prefix highlight like the screenshot, or to make it distinguishable from the prefix highlight like the source file.

**Comment by arcticicestudio** [comment]
The screenshot and color definitions are correct, the colors are switched for the status bar integration, otherwise the arrow (``) would be colorized black.

![gh-9-scrot-color-switch](https://user-images.githubusercontent.com/7836623/28239545-fe56ff94-696e-11e7-87b8-e37708f12a9d.png)

**Comment by tsroten** [comment]
Ah, yes, I see. Thanks for the clarification!

So, when the status content is turned off, the colors for the copy mode indicator are inverted. I'll try to submit a pull request to fix that.

**Comment by arcticicestudio** [comment]
This has been resolved in #11 which splitted the definition for the `copy-mode` indicator into separate files based on the user configuration.

**Comment by arcticicestudio** [comment]
Superseded by #11
